#!/bin/bash

export EID=e0593aad560b0b3d6fdf46fa1906330c
export DS="http://localhost"
export AUTH_DB="http://admin:rm@localhost"
export WEBAPP_ENABLED=true
export WEBAPP_URL=http://localhost:8181
export STG_EID="34e6c0a772cc3cc6b847f91e00b29688"
export STG_DS="http://ds.4pax.com"
export GOPATH=$HOME/Documents/go
export EDITOR=mcedit
export PATH=/Users/sel/Documents/go/go_appengine:$PATH
export DRONE_HOST=http://localhost:8000
