#!/bin/bash

export EID=5c46f0fab07b397f8a520a853c0007a7
export DS="http://localhost"
export AUTH_DB="http://admin:rm@localhost"
export WEBAPP_ENABLED=true
export WEBAPP_URL=http://localhost:8181
export STG_EID="34e6c0a772cc3cc6b847f91e00b29688"
export STG_DS="http://ds.4pax.com"
export GOPATH=$HOME/Documents/go
export EDITOR=mcedit
export PATH=/Users/sel/Documents/go/go_appengine:$PATH
export DRONE_HOST=http://localhost:8000
