;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        ivy-backward-delete-char
        kill-region
        markdown-cycle
        markdown-exdent-or-delete
        markdown-outdent-or-delete
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        org-self-insert-command
        org-yank
        swiper
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        fc-deploy
        handle-switch-frame
        ido-find-file
        org-return-indent
        scroll-down-line
        scroll-up-line
        wdired-finish-edit
        ))
