;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        diredp-next-line
        emmet-expand-line
        erlang-electric-semicolon
        helm-projectile-find-file
        indent-for-tab-command
        ivy-backward-delete-char
        kill-region
        markdown-cycle
        markdown-exdent-or-delete
        markdown-outdent-or-delete
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        org-beginning-of-line
        org-cycle
        org-self-insert-command
        org-shiftmetaleft
        org-todo
        org-yank
        revert-buffer
        search-forward
        smex
        swiper
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        fc-deploy
        handle-switch-frame
        ido-find-file
        new-frame
        org-return-indent
        scroll-down-line
        scroll-up-line
        wdired-finish-edit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))
